/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as UploadJobsIndexRouteImport } from './routes/upload-jobs/index'
import { Route as TrainingWeeksIndexRouteImport } from './routes/training-weeks/index'
import { Route as SystemPromptsIndexRouteImport } from './routes/system-prompts/index'
import { Route as UploadJobsCompareRouteImport } from './routes/upload-jobs/compare'
import { Route as UploadJobsIdRouteImport } from './routes/upload-jobs/$id'
import { Route as TrainingWeeksWeekStartsOnRouteImport } from './routes/training-weeks/$weekStartsOn'
import { Route as SystemPromptsSlugRouteImport } from './routes/system-prompts/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadJobsIndexRoute = UploadJobsIndexRouteImport.update({
  id: '/upload-jobs/',
  path: '/upload-jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingWeeksIndexRoute = TrainingWeeksIndexRouteImport.update({
  id: '/training-weeks/',
  path: '/training-weeks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemPromptsIndexRoute = SystemPromptsIndexRouteImport.update({
  id: '/system-prompts/',
  path: '/system-prompts/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadJobsCompareRoute = UploadJobsCompareRouteImport.update({
  id: '/upload-jobs/compare',
  path: '/upload-jobs/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadJobsIdRoute = UploadJobsIdRouteImport.update({
  id: '/upload-jobs/$id',
  path: '/upload-jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingWeeksWeekStartsOnRoute =
  TrainingWeeksWeekStartsOnRouteImport.update({
    id: '/training-weeks/$weekStartsOn',
    path: '/training-weeks/$weekStartsOn',
    getParentRoute: () => rootRouteImport,
  } as any)
const SystemPromptsSlugRoute = SystemPromptsSlugRouteImport.update({
  id: '/system-prompts/$slug',
  path: '/system-prompts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/system-prompts/$slug': typeof SystemPromptsSlugRoute
  '/training-weeks/$weekStartsOn': typeof TrainingWeeksWeekStartsOnRoute
  '/upload-jobs/$id': typeof UploadJobsIdRoute
  '/upload-jobs/compare': typeof UploadJobsCompareRoute
  '/system-prompts/': typeof SystemPromptsIndexRoute
  '/training-weeks/': typeof TrainingWeeksIndexRoute
  '/upload-jobs/': typeof UploadJobsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/system-prompts/$slug': typeof SystemPromptsSlugRoute
  '/training-weeks/$weekStartsOn': typeof TrainingWeeksWeekStartsOnRoute
  '/upload-jobs/$id': typeof UploadJobsIdRoute
  '/upload-jobs/compare': typeof UploadJobsCompareRoute
  '/system-prompts': typeof SystemPromptsIndexRoute
  '/training-weeks': typeof TrainingWeeksIndexRoute
  '/upload-jobs': typeof UploadJobsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/system-prompts/$slug': typeof SystemPromptsSlugRoute
  '/training-weeks/$weekStartsOn': typeof TrainingWeeksWeekStartsOnRoute
  '/upload-jobs/$id': typeof UploadJobsIdRoute
  '/upload-jobs/compare': typeof UploadJobsCompareRoute
  '/system-prompts/': typeof SystemPromptsIndexRoute
  '/training-weeks/': typeof TrainingWeeksIndexRoute
  '/upload-jobs/': typeof UploadJobsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/system-prompts/$slug'
    | '/training-weeks/$weekStartsOn'
    | '/upload-jobs/$id'
    | '/upload-jobs/compare'
    | '/system-prompts/'
    | '/training-weeks/'
    | '/upload-jobs/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/system-prompts/$slug'
    | '/training-weeks/$weekStartsOn'
    | '/upload-jobs/$id'
    | '/upload-jobs/compare'
    | '/system-prompts'
    | '/training-weeks'
    | '/upload-jobs'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/system-prompts/$slug'
    | '/training-weeks/$weekStartsOn'
    | '/upload-jobs/$id'
    | '/upload-jobs/compare'
    | '/system-prompts/'
    | '/training-weeks/'
    | '/upload-jobs/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SystemPromptsSlugRoute: typeof SystemPromptsSlugRoute
  TrainingWeeksWeekStartsOnRoute: typeof TrainingWeeksWeekStartsOnRoute
  UploadJobsIdRoute: typeof UploadJobsIdRoute
  UploadJobsCompareRoute: typeof UploadJobsCompareRoute
  SystemPromptsIndexRoute: typeof SystemPromptsIndexRoute
  TrainingWeeksIndexRoute: typeof TrainingWeeksIndexRoute
  UploadJobsIndexRoute: typeof UploadJobsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-jobs/': {
      id: '/upload-jobs/'
      path: '/upload-jobs'
      fullPath: '/upload-jobs/'
      preLoaderRoute: typeof UploadJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-weeks/': {
      id: '/training-weeks/'
      path: '/training-weeks'
      fullPath: '/training-weeks/'
      preLoaderRoute: typeof TrainingWeeksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-prompts/': {
      id: '/system-prompts/'
      path: '/system-prompts'
      fullPath: '/system-prompts/'
      preLoaderRoute: typeof SystemPromptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-jobs/compare': {
      id: '/upload-jobs/compare'
      path: '/upload-jobs/compare'
      fullPath: '/upload-jobs/compare'
      preLoaderRoute: typeof UploadJobsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-jobs/$id': {
      id: '/upload-jobs/$id'
      path: '/upload-jobs/$id'
      fullPath: '/upload-jobs/$id'
      preLoaderRoute: typeof UploadJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-weeks/$weekStartsOn': {
      id: '/training-weeks/$weekStartsOn'
      path: '/training-weeks/$weekStartsOn'
      fullPath: '/training-weeks/$weekStartsOn'
      preLoaderRoute: typeof TrainingWeeksWeekStartsOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-prompts/$slug': {
      id: '/system-prompts/$slug'
      path: '/system-prompts/$slug'
      fullPath: '/system-prompts/$slug'
      preLoaderRoute: typeof SystemPromptsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SystemPromptsSlugRoute: SystemPromptsSlugRoute,
  TrainingWeeksWeekStartsOnRoute: TrainingWeeksWeekStartsOnRoute,
  UploadJobsIdRoute: UploadJobsIdRoute,
  UploadJobsCompareRoute: UploadJobsCompareRoute,
  SystemPromptsIndexRoute: SystemPromptsIndexRoute,
  TrainingWeeksIndexRoute: TrainingWeeksIndexRoute,
  UploadJobsIndexRoute: UploadJobsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
